### ISSUE TITLE
graphics_main.c init functions

### ISSUE THREAD

**Issue by hdieset** [Mathieu96/fatherload#9]
As far as I can see, both `config_main_background` and `init_main_bg` are doing the same things and the functions should wither be merged or renamed.

**Comment by Mathieu96** [comment]
No, config_main_bg is configuring the kinds of backgrounds (the mode, the number of backgrounds to activate, copy in VRAMs the relevant data) whereas init will set the background the default state when beginning/restarting the game, because in case a "restart", we don't need to set again the backgrounds nor copy again the data in VRAMs.

**Comment by hdieset** [comment]
Aha, I see. Then it's fine! :)
